# -*- coding: utf-8 -*-
"""phonebook(.csv).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S1KqUuhtmAW63loq7xp9RH3rYVRY_Szf
"""

import csv

file = "phone_book.csv"     # The name of the our file
field_names = ['Name', 'Last_name', 'Number']   # The names of the columns
main_contacts = {        
        "Ambulance": 112 ,
        "Police": 110
    }

def listing():
        # Listing all records
        print("~ ~ ~ Your Phonebook ~ ~ ~")
        with open(file) as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                print(row['Name'], row['Last_name'], row['Number']) 

def search_record(name, last_name, number):   # This function is used inside the 'add_record' function
    with open(file,'r', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            if row['Name'] == name and row['Last_name'] == last_name and row['Number'] == number:
                return True
        return False


def add_record():
    try:
        # Adding new record
        with open(file,'a',newline='') as csvfile:
            if csvfile.tell() == 0:    # if the file is empty, write column headers first
                writer = csv.DictWriter(csvfile, fieldnames=field_names)
                writer.writeheader()
            while True:
                name = input("Please enter a name to add: ").title().strip()
                last_name = input('Please enter a last name: ').title().strip()
                number = input("Please enter the number: ").strip()
                # Check if the record already exists
                if search_record(name, last_name, number):
                    print(f"{name} {last_name} is already in your phone book.")
                # Check if the input is valid
                elif not name.isalpha() or not last_name.isalpha() or not number.isdigit():
                    print("Please enter valid information.")
                else:
                    writer = csv.DictWriter(csvfile, fieldnames=field_names)
                    writer.writerow({'Name':name, 'Last_name': last_name, 'Number':number})
                    print(f'{name} {last_name} has been added to your phone book.') 
                    break
    except Exception as e:
        print("There is a mistake:", e)

def searching():
    try:
        with open(file,'r', newline='') as csvfile:
            search = input('Please enter a name to search: ').title().strip()
            reader = csv.DictReader(csvfile)
            results = []
            for i in reader:
                if i['Name'] == search:
                    results.append(i)
            if len(results) == 0:
                print(f"No record found with this name: {search}")
            elif len(results) == 1:
                print(results[0]['Name'], results[0]['Last_name'],':', results[0]['Number'])
            else:
                print(f"Multiple records found with name: {search}")
                for i, result in enumerate(results):
                    print(f"{i+1}. {result['Name']} {result['Last_name']}: {result['Number']}")
                # choice = input("Please select a record (1-{}): ".format(len(results)))
                # try:
                #     choice = int(choice)
                #     if choice > 0 and choice <= len(results):
                #         print(results[choice-1]['Name'], results[choice-1]['Last_name'],':', results[choice-1]['Number'])
                #     else:
                #         print("Invalid choice, please try again.")
                # except ValueError:
                #     print("Invalid choice, please try again.")
    except Exception as e:
        print(f'There is a mistake! : {e}')


def delete():    # deletes a record from the file
    try:
        with open(file) as csvfile:
            reader = csv.DictReader(csvfile)
            rows = []
            delete_name = input('Please enter a name to delete..: ').title().strip()
            delete_last_name = input('Please enter the last name..: ').title().strip()
            record_deleted = False
            for row in reader:
                if row['Name'] == delete_name and row['Last_name'] == delete_last_name:
                    record_deleted = True
                else:
                    rows.append(row)
                    
            if not record_deleted:
                print(f'No record found with this name: {delete_name} {delete_last_name}.')
                
            print(f'Are you sure you want to delete this/these record(s): {delete_name} {delete_last_name}?')
            confirmation = input('Please enter Y or N: ')
            if confirmation.upper() == 'Y':
                print(f'{delete_name} {delete_last_name} has been deleted!')
                with open(file, 'w', newline='') as csvfile:
                    writer = csv.DictWriter(csvfile, fieldnames=field_names)
                    writer.writeheader()
                    for row in rows:
                        writer.writerow(row)
                     
    except Exception as e:
        print(f'There is a mistake! : {e}')


    
def update():     # updates a record 
    try:
        with open(file) as csvfile:
            reader = csv.DictReader(csvfile)
            rows = list(reader)
            update_name = input('Please enter a name to update the record..: ').title().strip()
            update_last_name = input('Please enter the last name..: ').title().strip()
            for row in rows:
                if row['Name'] == update_name and row['Last_name'] == update_last_name:
                    print("Updating...: ", row['Name'], row['Last_name'])
                    row['Name'] = input('Please enter a new name..: ').title().strip()
                    row['Last_name'] = input('Please enter a new last name..: ').title().strip()
                    row['Number'] = int(input('Please enter a new number..: '))
                    print('Updated successfully!')
                    break
            else:
                print('There is no such record available!')

        with open(file,'w', newline='') as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=field_names)
            writer.writeheader()
            for row in rows:
                writer.writerow(row) 

    except Exception as e:
        print(f'There is a mistake! : {e}')

while True:
    print("\n------ Welcome to the Student Tracking Program! ------")
    print("1. Add a new record")
    print("2. Delete a record")
    print("3. Update enrollment")
    print("4. Search a record")
    print("5. Show the phone book")
    print("6. Exit\n")
    choice = input("Your choice..: ")

    if choice == "1":
        add_record()

    elif choice == "2":
        delete()

    elif choice == "3":
        update()

    elif choice == "4":
        searching()
    
    elif choice == "5":
        listing()
    
    elif choice == "6":
        print("Exiting the program...")
        break

    else:
        print("Invalid input. If you want to exit, please enter number '6'!")